### ISSUE TITLE
Отсутствует функция

### ISSUE THREAD

**Issue by sawich** [rw-mp/modules-api#7]
В примере, 20я строка, используется функция **print**, но с последним обновлением её больше нет.

`API::GetModule ().print (" CPP module has been loaded!");`

**Comment by 0x452** [comment]
Есть функция printf

**Comment by SavageDD** [comment]
> Есть функция printf

Есть std::cout :3

**Comment by teredokot** [comment]
> 
> 
> > Есть функция printf
> 
> Есть std::cout :3

Она не печатает в лог файл.
